package humanresourcesemployee;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import HumanResources.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.03.04 20:17:05 // Generated by ComTest
 *
 */
public class EmployeeTest {
}